# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calAv_cpp <- function(v, X) {
    .Call('_Palette_calAv_cpp', PACKAGE = 'Palette', v, X)
}

GetS <- function(X, K, DVec, lambda, batch_size = 100000L) {
    .Call('_Palette_GetS', PACKAGE = 'Palette', X, K, DVec, lambda, batch_size)
}

GetS_new <- function(X, K, B, lambda, batch_size = 50000L) {
    .Call('_Palette_GetS_new', PACKAGE = 'Palette', X, K, B, lambda, batch_size)
}

Getmat <- function(X, K, B, batch_size = 10000L) {
    .Call('_Palette_Getmat', PACKAGE = 'Palette', X, K, B, batch_size)
}

FindMedian_self <- function(X, idx) {
    .Call('_Palette_FindMedian_self', PACKAGE = 'Palette', X, idx)
}

FindMedian <- function(X, idx1, idx2) {
    .Call('_Palette_FindMedian', PACKAGE = 'Palette', X, idx1, idx2)
}

PairwiseKernel_norm <- function(sim, groupsim, idx1, idx2, seed) {
    .Call('_Palette_PairwiseKernel_norm', PACKAGE = 'Palette', sim, groupsim, idx1, idx2, seed)
}

Insert_submat <- function(X, submat, idx, scale, scaler) {
    .Call('_Palette_Insert_submat', PACKAGE = 'Palette', X, submat, idx, scale, scaler)
}

SubKernel <- function(x, p, i, q, k) {
    .Call('_Palette_SubKernel', PACKAGE = 'Palette', x, p, i, q, k)
}

FindGroupLink <- function(X, row_mat, col_mat, Angle_var = 15, max_Angle = 40) {
    .Call('_Palette_FindGroupLink', PACKAGE = 'Palette', X, row_mat, col_mat, Angle_var, max_Angle)
}

sKernel_norm <- function(N_list, N, clust, idx) {
    .Call('_Palette_sKernel_norm', PACKAGE = 'Palette', N_list, N, clust, idx)
}

modal_infer_one_one <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_Palette_modal_infer_one_one', PACKAGE = 'Palette', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

modal_infer_one_multi <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_Palette_modal_infer_one_multi', PACKAGE = 'Palette', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

modal_infer_multi_one <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_Palette_modal_infer_multi_one', PACKAGE = 'Palette', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

modal_infer_multi_multi <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_Palette_modal_infer_multi_multi', PACKAGE = 'Palette', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

elementwiseMultiplySp <- function(A, B) {
    .Call('_Palette_elementwiseMultiplySp', PACKAGE = 'Palette', A, B)
}

filter_SNN <- function(SNN, idx, meta_list) {
    .Call('_Palette_filter_SNN', PACKAGE = 'Palette', SNN, idx, meta_list)
}

K_SNN <- function(SNN, idx, k, lambda) {
    .Call('_Palette_K_SNN', PACKAGE = 'Palette', SNN, idx, k, lambda)
}

silhouette_cpp <- function(labels, X) {
    .Call('_Palette_silhouette_cpp', PACKAGE = 'Palette', labels, X)
}

