# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calAv_cpp <- function(v, X) {
    .Call('_PaletteSC_calAv_cpp', PACKAGE = 'PaletteSC', v, X)
}

GetS <- function(X, K, DVec, lambda, batch_size = 100000L) {
    .Call('_PaletteSC_GetS', PACKAGE = 'PaletteSC', X, K, DVec, lambda, batch_size)
}

GetS_new <- function(X, K, B, lambda, batch_size = 50000L) {
    .Call('_PaletteSC_GetS_new', PACKAGE = 'PaletteSC', X, K, B, lambda, batch_size)
}

Getmat <- function(X, K, B, batch_size = 10000L) {
    .Call('_PaletteSC_Getmat', PACKAGE = 'PaletteSC', X, K, B, batch_size)
}

FindMedian_self <- function(X, idx) {
    .Call('_PaletteSC_FindMedian_self', PACKAGE = 'PaletteSC', X, idx)
}

FindMedian <- function(X, idx1, idx2) {
    .Call('_PaletteSC_FindMedian', PACKAGE = 'PaletteSC', X, idx1, idx2)
}

PairwiseKernel_norm <- function(sim, groupsim, idx1, idx2, seed) {
    .Call('_PaletteSC_PairwiseKernel_norm', PACKAGE = 'PaletteSC', sim, groupsim, idx1, idx2, seed)
}

Insert_submat <- function(X, submat, idx, scale, scaler) {
    .Call('_PaletteSC_Insert_submat', PACKAGE = 'PaletteSC', X, submat, idx, scale, scaler)
}

SubKernel <- function(x, p, i, q, k) {
    .Call('_PaletteSC_SubKernel', PACKAGE = 'PaletteSC', x, p, i, q, k)
}

FindGroupLink <- function(X, row_mat, col_mat, Angle_var = 15, max_Angle = 40) {
    .Call('_PaletteSC_FindGroupLink', PACKAGE = 'PaletteSC', X, row_mat, col_mat, Angle_var, max_Angle)
}

sKernel_norm <- function(N_list, N, clust, idx) {
    .Call('_PaletteSC_sKernel_norm', PACKAGE = 'PaletteSC', N_list, N, clust, idx)
}

modal_infer_one_one <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_PaletteSC_modal_infer_one_one', PACKAGE = 'PaletteSC', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

modal_infer_one_multi <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_PaletteSC_modal_infer_one_multi', PACKAGE = 'PaletteSC', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

modal_infer_multi_one <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_PaletteSC_modal_infer_multi_one', PACKAGE = 'PaletteSC', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

modal_infer_multi_multi <- function(X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k) {
    .Call('_PaletteSC_modal_infer_multi_multi', PACKAGE = 'PaletteSC', X, Y, k, L2, Z, T, do_scaler, scaler_k, do_var, var_k)
}

filter_SNN <- function(SNN, idx, meta_list) {
    .Call('_PaletteSC_filter_SNN', PACKAGE = 'PaletteSC', SNN, idx, meta_list)
}

K_SNN <- function(SNN, idx, k, lambda) {
    .Call('_PaletteSC_K_SNN', PACKAGE = 'PaletteSC', SNN, idx, k, lambda)
}

silhouette_cpp <- function(labels, X) {
    .Call('_PaletteSC_silhouette_cpp', PACKAGE = 'PaletteSC', labels, X)
}

